import type { Category, HelpRequest, Job, RequestComment, Chat } from "@/types";

export const categories: { id: Category; label: string; icon: string; description: string }[] = [
  { id: "reparaciones", label: "Reparaciones", icon: "🔧", description: "Electrodomésticos, plomería, electricidad" },
  { id: "transporte", label: "Transporte", icon: "🚗", description: "Traslados, mudanzas, acarreos" },
  { id: "mascotas", label: "Mascotas", icon: "🐕", description: "Mascotas perdidas, paseos, cuidado" },
  { id: "compras", label: "Compras", icon: "🛒", description: "Supermercado, farmacia, encargos" },
  { id: "servicios", label: "Servicios", icon: "🏠", description: "Plomero, electricista, albañil" },
  { id: "comunidad", label: "Comunidad", icon: "📢", description: "Avisos, alertas, novedades del barrio" },
];

export const mockRequests: HelpRequest[] = [
  {
    id: "1",
    title: "Necesito reparar mi lavadora",
    description: "Mi lavadora no centrifuga bien, hace un ruido extraño. ¿Alguien sabe de un técnico que pueda venir a revisarla? Está en buenas condiciones generalmente, solo empezó con este problema hace unos días.",
    category: "reparaciones",
    status: "abierta",
    author: { id: "u1", name: "María García", avatar: "👩" },
    location: "Av. Libertador, Centro",
    createdAt: "2026-09-14T10:30:00Z",
    responses: 3,
  },
  {
    id: "2",
    title: "¿Alguien puede ayudarme a pasar corriente?",
    description: "Se me descargó el auto y no tengo cables. ¿Alguien del barrio tiene cables para pasar corriente? Estoy estacionado frente al edificio 4 de las Parcelas.",
    category: "transporte",
    status: "abierta",
    author: { id: "u2", name: "Carlos López", avatar: "👨" },
    location: "Las Parcelas, Edif. 4",
    createdAt: "2026-09-14T09:15:00Z",
    responses: 1,
  },
  {
    id: "3",
    title: "Necesito transportar un mueble grande",
    description: "Compré un sillón en Marketplace y necesito traerlo desde el centro de la ciudad. Mide approx. 2m x 1m. ¿Alguien tiene camioneta y me puede ayudar? Se lo agradecería mucho.",
    category: "transporte",
    status: "abierta",
    author: { id: "u3", name: "Ana Martínez", avatar: "👩‍🦰" },
    location: "Col. Los Pinos",
    createdAt: "2026-09-13T18:00:00Z",
    responses: 2,
  },
  {
    id: "4",
    title: "Encontré este perro, ¿alguien lo reconoce?",
    description: "Encontré un perro mestizo color café cerca del parque principal. No trae collar ni placa. Se ve bien cuidado, seguro tiene dueño. Está tranquilo y es cariñoso. Por favor si lo reconoces contáctame.",
    category: "mascotas",
    status: "abierta",
    author: { id: "u4", name: "Pedro Sánchez", avatar: "👴" },
    location: "Parque Principal",
    createdAt: "2026-09-14T07:45:00Z",
    responses: 5,
  },
  {
    id: "5",
    title: "¿Alguien va al supermercado y puede traerme algo?",
    description: "Necesito que me traigan leche, pan y huevos. No puedo salir porque estoy cuidando a mi mamá. Agradecería mucho si alguien puede traerme estas cosas del Walmart. Les pago en efectivo cuando lleguen.",
    category: "compras",
    status: "abierta",
    author: { id: "u5", name: "Laura Rodríguez", avatar: "👩‍🦱" },
    location: "Fracc. San Miguel",
    createdAt: "2026-09-14T08:00:00Z",
    responses: 4,
  },
  {
    id: "6",
    title: "Busco plomero de confianza",
    description: "Tengo una fuga de agua en el baño que no para. Necesito un plomero que pueda venir hoy o mañana a arreglarlo. ¿Alguien tiene a alguien de confianza que me pueda recomendar?",
    category: "servicios",
    status: "en_progreso",
    author: { id: "u6", name: "Roberto Díaz", avatar: "🧔" },
    location: "Calle 5 de Mayo, Centro",
    createdAt: "2026-09-13T14:20:00Z",
    responses: 3,
  },
  {
    id: "7",
    title: "Se fue el agua en toda la cuadra",
    description: "Ya van 3 días sin agua en la cuadra de Joaquín Contreras entre 2 y 3 de Abril. Ya llamé a la compañía y dicen que están reparando una tubería. ¿Alguien tiene más información o sabe cuándo vuelve?",
    category: "comunidad",
    status: "abierta",
    author: { id: "u7", name: "Fernando Torres", avatar: "🧑" },
    location: "Joaquín Contreras, Centro",
    createdAt: "2026-09-12T11:00:00Z",
    responses: 8,
  },
  {
    id: "8",
    title: "Necesito electricista urgente",
    description: "Se me fue la luz en la casa, revisé el breaker y está bien pero no hay corriente en ninguna toma. Puede ser un problema de cableado interno. ¿Algún electricista que pueda venir a revisar?",
    category: "servicios",
    status: "completada",
    author: { id: "u8", name: "Isabel Vargas", avatar: "👵" },
    location: "Col. Esperanza",
    createdAt: "2026-09-11T16:30:00Z",
    responses: 2,
  },
];

export const mockJobs: Job[] = [
  {
    id: "j1",
    requestId: "1",
    helperId: "u10",
    helperName: "Roberto Méndez",
    helperAvatar: "🔧",
    status: "en_progreso",
    price: 450,
    scheduledFor: "2026-09-15T10:00:00Z",
    notes: "Tengo experiencia reparando lavadoras Samsung",
    acceptedAt: "2026-09-14T11:00:00Z",
  },
  {
    id: "j2",
    requestId: "5",
    helperId: "u11",
    helperName: "Laura Rodríguez",
    helperAvatar: "🛒",
    status: "aceptada",
    scheduledFor: "2026-09-15T14:00:00Z",
    notes: "Paso por el Walmart de las 3 a 5pm",
    acceptedAt: "2026-09-14T09:30:00Z",
  },
  {
    id: "j3",
    requestId: "6",
    helperId: "u12",
    helperName: "Fernando Castillo",
    helperAvatar: "🔧",
    status: "completada",
    price: 600,
    notes: "Ya se reparó la fuga del sifón del baño",
    acceptedAt: "2026-09-13T15:00:00Z",
  },
  {
    id: "j4",
    requestId: "8",
    helperId: "u13",
    helperName: "Manuel López",
    helperAvatar: "⚡",
    status: "completada",
    price: 350,
    notes: "Cableado del breaker principal reemplazado",
    acceptedAt: "2026-09-11T17:00:00Z",
  },
  {
    id: "j5",
    requestId: "2",
    helperId: "u14",
    helperName: "Diego Herrera",
    helperAvatar: "🚗",
    status: "cancelada",
    notes: "No pude acudir, mandé a un conocido",
    acceptedAt: "2026-09-14T09:45:00Z",
  },
  {
    id: "j6",
    requestId: "4",
    helperId: "u15",
    helperName: "Ana Martínez",
    helperAvatar: "🐕",
    status: "aceptada",
    scheduledFor: "2026-09-15T18:00:00Z",
    notes: "Puedo llevarlo al veterinario para que lo revisen",
    acceptedAt: "2026-09-14T08:15:00Z",
  },
];

export const mockComments: RequestComment[] = [
  {
    id: "c1",
    requestId: "1",
    author: "Roberto Méndez",
    authorAvatar: "🔧",
    content: "¿Qué marca es la lavadora? Algunas Samsung tienen un problema conocido con el motor de centrifugado.",
    status: "aprobado",
    createdAt: "2026-09-14T10:45:00Z",
  },
  {
    id: "c2",
    requestId: "1",
    author: "Sandra Paredes",
    authorAvatar: "👩‍🔧",
    content: "A mí me pasó algo similar y era el filtro de aspiración. Revísalo antes de llamar a un técnico, es fácil de limpiar.",
    status: "aprobado",
    createdAt: "2026-09-14T11:20:00Z",
  },
  {
    id: "c3",
    requestId: "4",
    author: "Juan Carlos Ruiz",
    authorAvatar: "🧑‍🦱",
    content: "Vi al perro cerca de la farmacia Guadalajara esta mañana. Creo que vivía por la calle Juárez.",
    status: "aprobado",
    createdAt: "2026-09-14T08:00:00Z",
  },
  {
    id: "c4",
    requestId: "7",
    author: "Patricia Morales",
    authorAvatar: "👩",
    content: "Las barangas siguen sin agua. ¿Alguien ya reclamó formalmente a la compañía?",
    status: "pendiente",
    createdAt: "2026-09-13T09:15:00Z",
  },
  {
    id: "c5",
    requestId: "7",
    author: "Carlos Vega",
    authorAvatar: "🧔",
    content: "Sí, ya fui a la preprocessing y dijeron que la reparación es hasta el viernes. Traigan cubetas mientras tanto.",
    status: "pendiente",
    createdAt: "2026-09-13T14:30:00Z",
  },
  {
    id: "c6",
    requestId: "3",
    author: "Roberto López",
    authorAvatar: "🚚",
    content: "Tengo una camioneta y puedo ayudarte el sábado en la mañana. ¿En qué parte del centro queda?",
    status: "oculto",
    createdAt: "2026-09-14T07:00:00Z",
  },
];

export const mockChats: Chat[] = [
  {
    id: "ch1",
    participantId: "u10",
    participantName: "Roberto Méndez",
    participantAvatar: "🔧",
    participantNeighborhood: "Centro",
    requestId: "1",
    requestTitle: "Necesito reparar mi lavadora",
    messages: [
      { id: "m1", senderId: "u10", content: "Hola María, vi tu solicitud sobre la lavadora. ¿Qué marca y modelo es?", sentAt: "2026-09-14T11:05:00Z", read: true },
      { id: "m2", senderId: "u1", content: "Hola Roberto, es una Samsung WF90. Hace como un ruido metálico cuando centrifuga.", sentAt: "2026-09-14T11:10:00Z", read: true },
      { id: "m3", senderId: "u10", content: "Conozco ese modelo, suele ser el rodamiento del tambor. Puedo ir mañana a revisarla. ¿Te parece a las 10am?", sentAt: "2026-09-14T11:12:00Z", read: true },
      { id: "m4", senderId: "u1", content: "Perfecto, te espero. Mi dirección es Av. Libertador 423, depto 2B.", sentAt: "2026-09-14T11:15:00Z", read: true },
      { id: "m5", senderId: "u10", content: "Anotado, ahí estaré. ¿Tiene acceso por la cochera o entro por la puerta principal?", sentAt: "2026-09-14T11:18:00Z", read: false },
    ],
  },
  {
    id: "ch2",
    participantId: "u4",
    participantName: "Pedro Sánchez",
    participantAvatar: "👴",
    participantNeighborhood: "Parque Principal",
    requestId: "4",
    requestTitle: "Encontré este perro, ¿alguien lo reconoce?",
    messages: [
      { id: "m6", senderId: "u4", content: "Gracias por compartir el aviso. ¿Viste al perro cerca de la iglesia o más hacia el parque?", sentAt: "2026-09-14T08:30:00Z", read: true },
      { id: "m7", senderId: "u9", content: "Fue más hacia la fuente del parque. Estaba muy tranquilo, como esperando a alguien.", sentAt: "2026-09-14T08:35:00Z", read: true },
      { id: "m8", senderId: "u4", content: "Creo que es de los vecinos de la calle Madero. Deja pregunto en el grupo del barrio.", sentAt: "2026-09-14T08:40:00Z", read: true },
    ],
  },
  {
    id: "ch3",
    participantId: "u12",
    participantName: "Fernando Castillo",
    participantAvatar: "🔧",
    participantNeighborhood: "Centro",
    requestId: "6",
    requestTitle: "Busco plomero de confianza",
    messages: [
      { id: "m9", senderId: "u12", content: "Hola Roberto, soy Fernando, plomero de oficio. ¿Dónde está la fuga exactamente?", sentAt: "2026-09-13T15:05:00Z", read: true },
      { id: "m10", senderId: "u6", content: "En el baño principal, detrás del lavabo. Se está formando un charco.", sentAt: "2026-09-13T15:10:00Z", read: true },
      { id: "m11", senderId: "u12", content: "Lo más probable es el sifón o la unión con la pared. Ya lo puedo ir a revisar. ¿Cuándo te conviene?", sentAt: "2026-09-13T15:12:00Z", read: true },
      { id: "m12", senderId: "u6", content: "Hoy en la tarde entre 4 y 6 te viene bien?", sentAt: "2026-09-13T15:15:00Z", read: true },
      { id: "m13", senderId: "u12", content: "Perfecto, ahí estaré. Cobro $600 la visita con mano de obra.", sentAt: "2026-09-13T15:18:00Z", read: true },
    ],
  },
];
