import type { Category, HelpRequest, Job, RequestComment, Chat } from "@/types";

export const categories: { id: Category; label: string; icon: string; description: string }[] = [
  { id: "repairs", label: "Repairs", icon: "🔧", description: "Appliances, plumbing, electricity" },
  { id: "transport", label: "Transport", icon: "🚗", description: "Rides, moves, hauling" },
  { id: "pets", label: "Pets", icon: "🐕", description: "Lost pets, walks, care" },
  { id: "groceries", label: "Groceries", icon: "🛒", description: "Supermarket, pharmacy, errands" },
  { id: "services", label: "Services", icon: "🏠", description: "Plumber, electrician, mason" },
  { id: "community", label: "Community", icon: "📢", description: "Announcements, alerts, neighborhood news" },
  { id: "carpentry", label: "Carpentry", icon: "🔨", description: "Woodworking, construction, repairs" },
];

export const mockRequests: HelpRequest[] = [
  {
    id: "1",
    title: "I need to repair my washing machine",
    description: "My washing machine isn't spinning well and makes a strange noise. Does anyone know a technician who could come check it? It's generally in good condition; it just started acting up a few days ago.",
    category: "repairs",
    status: "abierta",
    author: { id: "u1", name: "María García", avatar: "👩" },
    location: "Av. Libertador, Centro",
    createdAt: "2026-09-14T10:30:00Z",
    responses: 3,
  },
  {
    id: "2",
    title: "Can someone help me jump-start my car?",
    description: "My car battery died and I don't have jumper cables. Does anyone in the neighborhood have jumper cables? I'm parked in front of building 4 in Las Parcelas.",
    category: "transport",
    status: "abierta",
    author: { id: "u2", name: "Carlos López", avatar: "👨" },
    location: "Las Parcelas, Edif. 4",
    createdAt: "2026-09-14T09:15:00Z",
    responses: 1,
  },
  {
    id: "3",
    title: "I need to move a large piece of furniture",
    description: "I bought a sofa on Marketplace and need to bring it from downtown. It's about 2m x 1m. Does anyone have a truck and can help me? I'd really appreciate it.",
    category: "transport",
    status: "abierta",
    author: { id: "u3", name: "Ana Martínez", avatar: "👩‍🦰" },
    location: "Col. Los Pinos",
    createdAt: "2026-09-13T18:00:00Z",
    responses: 2,
  },
  {
    id: "4",
    title: "I found this dog, does anyone recognize him?",
    description: "I found a brown mixed-breed dog near the main park. No collar or tags. It looks well cared for, so it probably has an owner. He's calm and friendly. Please contact me if you recognize him.",
    category: "pets",
    status: "abierta",
    author: { id: "u4", name: "Pedro Sánchez", avatar: "👴" },
    location: "Parque Principal",
    createdAt: "2026-09-14T07:45:00Z",
    responses: 5,
  },
  {
    id: "5",
    title: "Is anyone going to the supermarket and could pick something up for me?",
    description: "I need milk, bread, and eggs brought to me. I can't leave because I'm taking care of my mom. I'd really appreciate it if someone could pick these up from Walmart. I'll pay cash when you arrive.",
    category: "groceries",
    status: "abierta",
    author: { id: "u5", name: "Laura Rodríguez", avatar: "👩‍🦱" },
    location: "Fracc. San Miguel",
    createdAt: "2026-09-14T08:00:00Z",
    responses: 4,
  },
  {
    id: "6",
    title: "Looking for a trustworthy plumber",
    description: "I have a water leak in the bathroom that won't stop. I need a plumber who can come today or tomorrow to fix it. Does anyone have someone trustworthy to recommend?",
    category: "services",
    status: "en_progreso",
    author: { id: "u6", name: "Roberto Díaz", avatar: "🧔" },
    location: "Calle 5 de Mayo, Centro",
    createdAt: "2026-09-13T14:20:00Z",
    responses: 3,
  },
  {
    id: "7",
    title: "The water went out on the whole block",
    description: "It's been 3 days without water on the Joaquín Contreras block between April 2nd and 3rd. I already called the company and they say they're repairing a pipe. Does anyone have more info or know when it's coming back?",
    category: "community",
    status: "abierta",
    author: { id: "u7", name: "Fernando Torres", avatar: "🧑" },
    location: "Joaquín Contreras, Centro",
    createdAt: "2026-09-12T11:00:00Z",
    responses: 8,
  },
  {
    id: "8",
    title: "I urgently need an electrician",
    description: "The power went out at home; I checked the breaker and it's fine, but there's no power in any outlet. It could be an internal wiring problem. Any electrician who can come check it?",
    category: "services",
    status: "completada",
    author: { id: "u8", name: "Isabel Vargas", avatar: "👵" },
    location: "Col. Esperanza",
    createdAt: "2026-09-11T16:30:00Z",
    responses: 2,
  },
];

export const mockJobs: Job[] = [
  {
    id: "j1",
    requestId: "1",
    helperId: "u10",
    helperName: "Roberto Méndez",
    helperAvatar: "🔧",
    status: "en_progreso",
    price: 450,
    scheduledFor: "2026-09-15T10:00:00Z",
    notes: "I have experience repairing Samsung washing machines",
    acceptedAt: "2026-09-14T11:00:00Z",
  },
  {
    id: "j2",
    requestId: "5",
    helperId: "u11",
    helperName: "Laura Rodríguez",
    helperAvatar: "🛒",
    status: "aceptada",
    scheduledFor: "2026-09-15T14:00:00Z",
    notes: "I'll stop by Walmart from 3 to 5pm",
    acceptedAt: "2026-09-14T09:30:00Z",
  },
  {
    id: "j3",
    requestId: "6",
    helperId: "u12",
    helperName: "Fernando Castillo",
    helperAvatar: "🔧",
    status: "completada",
    price: 600,
    notes: "The bathroom sink trap leak is fixed",
    acceptedAt: "2026-09-13T15:00:00Z",
  },
  {
    id: "j4",
    requestId: "8",
    helperId: "u13",
    helperName: "Manuel López",
    helperAvatar: "⚡",
    status: "completada",
    price: 350,
    notes: "Main breaker wiring replaced",
    acceptedAt: "2026-09-11T17:00:00Z",
  },
  {
    id: "j5",
    requestId: "2",
    helperId: "u14",
    helperName: "Diego Herrera",
    helperAvatar: "🚗",
    status: "cancelada",
    notes: "I couldn't make it, I sent an acquaintance",
    acceptedAt: "2026-09-14T09:45:00Z",
  },
  {
    id: "j6",
    requestId: "4",
    helperId: "u15",
    helperName: "Ana Martínez",
    helperAvatar: "🐕",
    status: "aceptada",
    scheduledFor: "2026-09-15T18:00:00Z",
    notes: "I can take him to the vet for a check-up",
    acceptedAt: "2026-09-14T08:15:00Z",
  },
];

export const mockComments: RequestComment[] = [
  {
    id: "c1",
    requestId: "1",
    author: "Roberto Méndez",
    authorAvatar: "🔧",
    content: "What brand is the washing machine? Some Samsungs have a known issue with the spin motor.",
    status: "aprobado",
    createdAt: "2026-09-14T10:45:00Z",
  },
  {
    id: "c2",
    requestId: "1",
    author: "Sandra Paredes",
    authorAvatar: "👩‍🔧",
    content: "Something similar happened to me and it was the drain filter. Check it before calling a technician; it's easy to clean.",
    status: "aprobado",
    createdAt: "2026-09-14T11:20:00Z",
  },
  {
    id: "c3",
    requestId: "4",
    author: "Juan Carlos Ruiz",
    authorAvatar: "🧑‍🦱",
    content: "I saw the dog near the Guadalajara pharmacy this morning. I think it lives around Juárez street.",
    status: "aprobado",
    createdAt: "2026-09-14T08:00:00Z",
  },
  {
    id: "c4",
    requestId: "7",
    author: "Patricia Morales",
    authorAvatar: "👩",
    content: "The neighborhood still has no water. Has anyone already filed a formal complaint with the company?",
    status: "pendiente",
    createdAt: "2026-09-13T09:15:00Z",
  },
  {
    id: "c5",
    requestId: "7",
    author: "Carlos Vega",
    authorAvatar: "🧔",
    content: "Yes, I already filed the complaint and they said the repair won't be until Friday. Bring buckets in the meantime.",
    status: "pendiente",
    createdAt: "2026-09-13T14:30:00Z",
  },
  {
    id: "c6",
    requestId: "3",
    author: "Roberto López",
    authorAvatar: "🚚",
    content: "I have a truck and can help you Saturday morning. What part of downtown is it?",
    status: "oculto",
    createdAt: "2026-09-14T07:00:00Z",
  },
];

export const mockChats: Chat[] = [
  {
    id: "ch1",
    participantId: "u10",
    participantName: "Roberto Méndez",
    participantAvatar: "🔧",
    participantNeighborhood: "Centro",
    requestId: "1",
    requestTitle: "I need to repair my washing machine",
    messages: [
      { id: "m1", senderId: "u10", content: "Hi María, I saw your request about the washing machine. What brand and model is it?", sentAt: "2026-09-14T11:05:00Z", read: true },
      { id: "m2", senderId: "u1", content: "Hi Roberto, it's a Samsung WF90. It makes a metallic noise when it spins.", sentAt: "2026-09-14T11:10:00Z", read: true },
      { id: "m3", senderId: "u10", content: "I know that model; it's usually the drum bearing. I can come check it tomorrow. Does 10am work for you?", sentAt: "2026-09-14T11:12:00Z", read: true },
      { id: "m4", senderId: "u1", content: "Perfect, I'll be waiting. My address is Av. Libertador 423, apt 2B.", sentAt: "2026-09-14T11:15:00Z", read: true },
      { id: "m5", senderId: "u10", content: "Got it, I'll be there. Is there access through the garage or do I come in through the front door?", sentAt: "2026-09-14T11:18:00Z", read: false },
    ],
  },
  {
    id: "ch2",
    participantId: "u4",
    participantName: "Pedro Sánchez",
    participantAvatar: "👴",
    participantNeighborhood: "Parque Principal",
    requestId: "4",
    requestTitle: "I found this dog, does anyone recognize him?",
    messages: [
      { id: "m6", senderId: "u4", content: "Thanks for sharing the post. Did you see the dog near the church or closer to the park?", sentAt: "2026-09-14T08:30:00Z", read: true },
      { id: "m7", senderId: "u9", content: "It was closer to the park fountain. It was very calm, like it was waiting for someone.", sentAt: "2026-09-14T08:35:00Z", read: true },
      { id: "m8", senderId: "u4", content: "I think it belongs to the neighbors on Madero street. Let me ask in the neighborhood group.", sentAt: "2026-09-14T08:40:00Z", read: true },
    ],
  },
  {
    id: "ch3",
    participantId: "u12",
    participantName: "Fernando Castillo",
    participantAvatar: "🔧",
    participantNeighborhood: "Centro",
    requestId: "6",
    requestTitle: "Looking for a trustworthy plumber",
    messages: [
      { id: "m9", senderId: "u12", content: "Hi Roberto, I'm Fernando, a plumber by trade. Where exactly is the leak?", sentAt: "2026-09-13T15:05:00Z", read: true },
      { id: "m10", senderId: "u6", content: "In the main bathroom, behind the sink. A puddle is forming.", sentAt: "2026-09-13T15:10:00Z", read: true },
      { id: "m11", senderId: "u12", content: "Most likely the trap or the wall connection. I can come check it now. When works for you?", sentAt: "2026-09-13T15:12:00Z", read: true },
      { id: "m12", senderId: "u6", content: "Does today between 4 and 6pm work for you?", sentAt: "2026-09-13T15:15:00Z", read: true },
      { id: "m13", senderId: "u12", content: "Perfect, I'll be there. I charge $600 per visit including labor.", sentAt: "2026-09-13T15:18:00Z", read: true },
    ],
  },
];
