import type {
  Category,
  HelpRequest,
  Job,
  RequestComment,
  Chat,
  JobListing,
  JobApplication,
  Review,
  WorkerProfile,
  WorkerReview,
} from "@/types";

export const categories: { id: Category; label: string; icon: string; description: string }[] = [
  { id: "repairs", label: "Repairs", icon: "🔧", description: "Appliances, plumbing, electricity" },
  { id: "transport", label: "Transport", icon: "🚗", description: "Rides, moves, hauling" },
  { id: "pets", label: "Pets", icon: "🐕", description: "Lost pets, walks, care" },
  { id: "groceries", label: "Groceries", icon: "🛒", description: "Supermarket, pharmacy, errands" },
  { id: "services", label: "Services", icon: "🏠", description: "Plumber, electrician, mason" },
  { id: "community", label: "Community", icon: "📢", description: "Announcements, alerts, neighborhood news" },
  { id: "carpentry", label: "Carpentry", icon: "🔨", description: "Woodworking, construction, repairs" },
  { id: "cleaning", label: "Cleaning", icon: "🧹", description: "Homes, offices, deep cleaning" },
  { id: "gardening", label: "Gardening", icon: "🌿", description: "Lawns, gardens, landscaping" },
  { id: "moving", label: "Moving", icon: "🚚", description: "Furniture, hauling, freight" },
];

export const mockRequests: HelpRequest[] = [
  {
    id: "1",
    title: "I need to repair my washing machine",
    description: "My washing machine isn't spinning well and makes a strange noise. Does anyone know a technician who could come check it? It's generally in good condition; it just started acting up a few days ago.",
    category: "repairs",
    status: "abierta",
    author: { id: "u1", name: "María García", avatar: "👩" },
    location: "Av. Libertador, Centro",
    createdAt: "2026-09-14T10:30:00Z",
    responses: 3,
  },
  {
    id: "2",
    title: "Can someone help me jump-start my car?",
    description: "My car battery died and I don't have jumper cables. Does anyone in the neighborhood have jumper cables? I'm parked in front of building 4 in Las Parcelas.",
    category: "transport",
    status: "abierta",
    author: { id: "u2", name: "Carlos López", avatar: "👨" },
    location: "Las Parcelas, Edif. 4",
    createdAt: "2026-09-14T09:15:00Z",
    responses: 1,
  },
  {
    id: "3",
    title: "I need to move a large piece of furniture",
    description: "I bought a sofa on Marketplace and need to bring it from downtown. It's about 2m x 1m. Does anyone have a truck and can help me? I'd really appreciate it.",
    category: "transport",
    status: "abierta",
    author: { id: "u3", name: "Ana Martínez", avatar: "👩‍🦰" },
    location: "Col. Los Pinos",
    createdAt: "2026-09-13T18:00:00Z",
    responses: 2,
  },
  {
    id: "4",
    title: "I found this dog, does anyone recognize him?",
    description: "I found a brown mixed-breed dog near the main park. No collar or tags. It looks well cared for, so it probably has an owner. He's calm and friendly. Please contact me if you recognize him.",
    category: "pets",
    status: "abierta",
    author: { id: "u4", name: "Pedro Sánchez", avatar: "👴" },
    location: "Parque Principal",
    createdAt: "2026-09-14T07:45:00Z",
    responses: 5,
  },
  {
    id: "5",
    title: "Is anyone going to the supermarket and could pick something up for me?",
    description: "I need milk, bread, and eggs brought to me. I can't leave because I'm taking care of my mom. I'd really appreciate it if someone could pick these up from Walmart. I'll pay cash when you arrive.",
    category: "groceries",
    status: "abierta",
    author: { id: "u5", name: "Laura Rodríguez", avatar: "👩‍🦱" },
    location: "Fracc. San Miguel",
    createdAt: "2026-09-14T08:00:00Z",
    responses: 4,
  },
  {
    id: "6",
    title: "Looking for a trustworthy plumber",
    description: "I have a water leak in the bathroom that won't stop. I need a plumber who can come today or tomorrow to fix it. Does anyone have someone trustworthy to recommend?",
    category: "services",
    status: "en_progreso",
    author: { id: "u6", name: "Roberto Díaz", avatar: "🧔" },
    location: "Calle 5 de Mayo, Centro",
    createdAt: "2026-09-13T14:20:00Z",
    responses: 3,
  },
  {
    id: "7",
    title: "The water went out on the whole block",
    description: "It's been 3 days without water on the Joaquín Contreras block between April 2nd and 3rd. I already called the company and they say they're repairing a pipe. Does anyone have more info or know when it's coming back?",
    category: "community",
    status: "abierta",
    author: { id: "u7", name: "Fernando Torres", avatar: "🧑" },
    location: "Joaquín Contreras, Centro",
    createdAt: "2026-09-12T11:00:00Z",
    responses: 8,
  },
  {
    id: "8",
    title: "I urgently need an electrician",
    description: "The power went out at home; I checked the breaker and it's fine, but there's no power in any outlet. It could be an internal wiring problem. Any electrician who can come check it?",
    category: "services",
    status: "completada",
    author: { id: "u8", name: "Isabel Vargas", avatar: "👵" },
    location: "Col. Esperanza",
    createdAt: "2026-09-11T16:30:00Z",
    responses: 2,
  },
];

export const mockJobs: Job[] = [
  {
    id: "j1",
    requestId: "1",
    helperId: "u10",
    helperName: "Roberto Méndez",
    helperAvatar: "🔧",
    status: "en_progreso",
    price: 450,
    scheduledFor: "2026-09-15T10:00:00Z",
    notes: "I have experience repairing Samsung washing machines",
    acceptedAt: "2026-09-14T11:00:00Z",
  },
  {
    id: "j2",
    requestId: "5",
    helperId: "u11",
    helperName: "Laura Rodríguez",
    helperAvatar: "🛒",
    status: "aceptada",
    scheduledFor: "2026-09-15T14:00:00Z",
    notes: "I'll stop by Walmart from 3 to 5pm",
    acceptedAt: "2026-09-14T09:30:00Z",
  },
  {
    id: "j3",
    requestId: "6",
    helperId: "u12",
    helperName: "Fernando Castillo",
    helperAvatar: "🔧",
    status: "completada",
    price: 600,
    notes: "The bathroom sink trap leak is fixed",
    acceptedAt: "2026-09-13T15:00:00Z",
  },
  {
    id: "j4",
    requestId: "8",
    helperId: "u13",
    helperName: "Manuel López",
    helperAvatar: "⚡",
    status: "completada",
    price: 350,
    notes: "Main breaker wiring replaced",
    acceptedAt: "2026-09-11T17:00:00Z",
  },
  {
    id: "j5",
    requestId: "2",
    helperId: "u14",
    helperName: "Diego Herrera",
    helperAvatar: "🚗",
    status: "cancelada",
    notes: "I couldn't make it, I sent an acquaintance",
    acceptedAt: "2026-09-14T09:45:00Z",
  },
  {
    id: "j6",
    requestId: "4",
    helperId: "u15",
    helperName: "Ana Martínez",
    helperAvatar: "🐕",
    status: "aceptada",
    scheduledFor: "2026-09-15T18:00:00Z",
    notes: "I can take him to the vet for a check-up",
    acceptedAt: "2026-09-14T08:15:00Z",
  },
];

export const mockComments: RequestComment[] = [
  {
    id: "c1",
    requestId: "1",
    author: "Roberto Méndez",
    authorAvatar: "🔧",
    content: "What brand is the washing machine? Some Samsungs have a known issue with the spin motor.",
    status: "aprobado",
    createdAt: "2026-09-14T10:45:00Z",
  },
  {
    id: "c2",
    requestId: "1",
    author: "Sandra Paredes",
    authorAvatar: "👩‍🔧",
    content: "Something similar happened to me and it was the drain filter. Check it before calling a technician; it's easy to clean.",
    status: "aprobado",
    createdAt: "2026-09-14T11:20:00Z",
  },
  {
    id: "c3",
    requestId: "4",
    author: "Juan Carlos Ruiz",
    authorAvatar: "🧑‍🦱",
    content: "I saw the dog near the Guadalajara pharmacy this morning. I think it lives around Juárez street.",
    status: "aprobado",
    createdAt: "2026-09-14T08:00:00Z",
  },
  {
    id: "c4",
    requestId: "7",
    author: "Patricia Morales",
    authorAvatar: "👩",
    content: "The neighborhood still has no water. Has anyone already filed a formal complaint with the company?",
    status: "pendiente",
    createdAt: "2026-09-13T09:15:00Z",
  },
  {
    id: "c5",
    requestId: "7",
    author: "Carlos Vega",
    authorAvatar: "🧔",
    content: "Yes, I already filed the complaint and they said the repair won't be until Friday. Bring buckets in the meantime.",
    status: "pendiente",
    createdAt: "2026-09-13T14:30:00Z",
  },
  {
    id: "c6",
    requestId: "3",
    author: "Roberto López",
    authorAvatar: "🚚",
    content: "I have a truck and can help you Saturday morning. What part of downtown is it?",
    status: "oculto",
    createdAt: "2026-09-14T07:00:00Z",
  },
];

export const mockChats: Chat[] = [
  {
    id: "ch1",
    participantId: "u10",
    participantName: "Roberto Méndez",
    participantAvatar: "🔧",
    participantNeighborhood: "Centro",
    requestId: "1",
    requestTitle: "I need to repair my washing machine",
    messages: [
      { id: "m1", senderId: "u10", content: "Hi María, I saw your request about the washing machine. What brand and model is it?", sentAt: "2026-09-14T11:05:00Z", read: true },
      { id: "m2", senderId: "u1", content: "Hi Roberto, it's a Samsung WF90. It makes a metallic noise when it spins.", sentAt: "2026-09-14T11:10:00Z", read: true },
      { id: "m3", senderId: "u10", content: "I know that model; it's usually the drum bearing. I can come check it tomorrow. Does 10am work for you?", sentAt: "2026-09-14T11:12:00Z", read: true },
      { id: "m4", senderId: "u1", content: "Perfect, I'll be waiting. My address is Av. Libertador 423, apt 2B.", sentAt: "2026-09-14T11:15:00Z", read: true },
      { id: "m5", senderId: "u10", content: "Got it, I'll be there. Is there access through the garage or do I come in through the front door?", sentAt: "2026-09-14T11:18:00Z", read: false },
    ],
  },
  {
    id: "ch2",
    participantId: "u4",
    participantName: "Pedro Sánchez",
    participantAvatar: "👴",
    participantNeighborhood: "Parque Principal",
    requestId: "4",
    requestTitle: "I found this dog, does anyone recognize him?",
    messages: [
      { id: "m6", senderId: "u4", content: "Thanks for sharing the post. Did you see the dog near the church or closer to the park?", sentAt: "2026-09-14T08:30:00Z", read: true },
      { id: "m7", senderId: "u9", content: "It was closer to the park fountain. It was very calm, like it was waiting for someone.", sentAt: "2026-09-14T08:35:00Z", read: true },
      { id: "m8", senderId: "u4", content: "I think it belongs to the neighbors on Madero street. Let me ask in the neighborhood group.", sentAt: "2026-09-14T08:40:00Z", read: true },
    ],
  },
  {
    id: "ch3",
    participantId: "u12",
    participantName: "Fernando Castillo",
    participantAvatar: "🔧",
    participantNeighborhood: "Centro",
    requestId: "6",
    requestTitle: "Looking for a trustworthy plumber",
    messages: [
      { id: "m9", senderId: "u12", content: "Hi Roberto, I'm Fernando, a plumber by trade. Where exactly is the leak?", sentAt: "2026-09-13T15:05:00Z", read: true },
      { id: "m10", senderId: "u6", content: "In the main bathroom, behind the sink. A puddle is forming.", sentAt: "2026-09-13T15:10:00Z", read: true },
      { id: "m11", senderId: "u12", content: "Most likely the trap or the wall connection. I can come check it now. When works for you?", sentAt: "2026-09-13T15:12:00Z", read: true },
      { id: "m12", senderId: "u6", content: "Does today between 4 and 6pm work for you?", sentAt: "2026-09-13T15:15:00Z", read: true },
      { id: "m13", senderId: "u12", content: "Perfect, I'll be there. I charge $600 per visit including labor.", sentAt: "2026-09-13T15:18:00Z", read: true },
    ],
  },
];

export const mockJobListings: JobListing[] = [
  {
    id: "t1",
    title: "Movers helper for Saturday move",
    description:
      "We are moving from Zona 10 to Zona 15 next Saturday. We need two people to help pack boxes, carry furniture, and load/unload the truck. It's a 3.5 km trip between the two apartments. Please arrive with comfortable clothes; we'll have water and snacks.",
    category: "moving",
    modality: "por_dia",
    amount: 250,
    units: 1,
    negotiable: false,
    includesTransport: false,
    includesMaterials: false,
    includesMeals: false,
    startDate: "2026-09-26",
    schedule: "8:00 AM – 4:00 PM",
    zone: "Zona 10",
    city: "Ciudad de Guatemala",
    peopleNeeded: 2,
    requirements: "Able to lift heavy furniture and follow instructions.",
    status: "publicado",
    publisher: { id: "u16", name: "Julio Recinos", avatar: "🧑" },
    publisherVerified: true,
    applicationsCount: 3,
    createdAt: "2026-09-20T09:00:00Z",
  },
  {
    id: "t2",
    title: "Gardening helper: mow lawn and clean garden",
    description:
      "Our house garden got out of hand. I need someone to cut the grass, trim the edges, and clean up the patio for 4 hours. Tools and the mower I have at home. A basic understanding of plants is a plus.",
    category: "gardening",
    modality: "por_hora",
    amount: 40,
    units: 4,
    negotiable: false,
    includesTransport: false,
    includesMaterials: true,
    includesMeals: false,
    startDate: "2026-09-25",
    schedule: "8:00 AM – 12:00 PM",
    zone: "Zona 15",
    city: "Ciudad de Guatemala",
    peopleNeeded: 1,
    requirements: "Basic gardening experience.",
    status: "publicado",
    publisher: { id: "u17", name: "Carmen Ruiz", avatar: "👩‍🦱" },
    publisherVerified: true,
    applicationsCount: 6,
    createdAt: "2026-09-20T14:20:00Z",
  },
  {
    id: "t3",
    title: "Biweekly cleaning for an apartment",
    description:
      "I'm looking for someone to deep-clean my one-bedroom apartment every two weeks. Cleaning supplies are included. We can agree on the exact day after the first visit. Consistency matters more than speed.",
    category: "cleaning",
    modality: "recurrente",
    amount: 250,
    frequency: "Every other Saturday",
    negotiable: true,
    includesTransport: false,
    includesMaterials: true,
    includesMeals: false,
    startDate: "2026-09-26",
    schedule: "7:00 AM – 11:00 AM",
    zone: "Zona 1",
    city: "Ciudad de Guatemala",
    peopleNeeded: 1,
    requirements: "Cleaning experience and references if possible.",
    status: "publicado",
    publisher: { id: "u18", name: "Laura Rodríguez", avatar: "👩‍🦱" },
    publisherVerified: true,
    applicationsCount: 4,
    createdAt: "2026-09-20T11:00:00Z",
  },
  {
    id: "t4",
    title: "Fix bedroom door and frame",
    description:
      "The bedroom door no longer closes properly and the wooden frame is split at the hinge. It's a standard hollow-core door. I can buy the materials myself or you can bring them and add the cost.",
    category: "carpentry",
    modality: "por_proyecto",
    amount: 300,
    negotiable: true,
    includesTransport: false,
    includesMaterials: false,
    includesMeals: false,
    startDate: "2026-09-24",
    schedule: "Flexible",
    zone: "Zona 4",
    city: "Ciudad de Guatemala",
    peopleNeeded: 1,
    requirements: "Carpentry experience with doors and frames.",
    status: "publicado",
    publisher: { id: "u19", name: "Roberto Díaz", avatar: "🧔" },
    publisherVerified: true,
    applicationsCount: 2,
    createdAt: "2026-09-19T16:30:00Z",
  },
  {
    id: "t5",
    title: "Warehouse helper for one week",
    description:
      "Our small warehouse needs an extra person for a week to organize shelves and prepare orders. Standing most of the day. Lunch is included. Weekly pay on Friday.",
    category: "services",
    modality: "por_semana",
    amount: 1200,
    units: 1,
    negotiable: false,
    includesTransport: false,
    includesMaterials: false,
    includesMeals: true,
    startDate: "2026-09-28",
    endDate: "2026-10-02",
    schedule: "9:00 AM – 5:00 PM",
    zone: "Zona 13",
    city: "Ciudad de Guatemala",
    peopleNeeded: 1,
    requirements: "Comfortable standing for long hours; punctuality.",
    status: "publicado",
    publisher: { id: "u20", name: "Isabel Vargas", avatar: "👵" },
    publisherVerified: true,
    applicationsCount: 8,
    createdAt: "2026-09-18T10:00:00Z",
  },
  {
    id: "t6",
    title: "Help unloading a delivery truck",
    description:
      "A delivery truck arrives Tuesday at noon with boxes for our store. I need one or two people for about 2 to 3 hours to unload and place the boxes in the back room.",
    category: "moving",
    modality: "por_hora",
    amount: 35,
    units: 3,
    negotiable: false,
    includesTransport: false,
    includesMaterials: false,
    includesMeals: false,
    startDate: "2026-09-23",
    schedule: "12:00 PM – 3:00 PM",
    zone: "Zona 9",
    city: "Ciudad de Guatemala",
    peopleNeeded: 2,
    status: "publicado",
    publisher: { id: "u21", name: "Héctor Molina", avatar: "👨" },
    publisherVerified: false,
    applicationsCount: 1,
    createdAt: "2026-09-17T09:30:00Z",
  },
  {
    id: "t7",
    title: "Electrician for a full wiring check",
    description:
      "The breakers trip when we use the laundry machine. We need an electrician to check the wiring and quote a repair. Nothing has burned yet, but we want to avoid a bigger problem.",
    category: "services",
    modality: "por_proyecto",
    amount: 450,
    negotiable: true,
    includesTransport: false,
    includesMaterials: false,
    includesMeals: false,
    startDate: "2026-09-22",
    schedule: "3:00 PM – 6:00 PM",
    zone: "Zona 5",
    city: "Ciudad de Guatemala",
    peopleNeeded: 1,
    requirements: "Licensed electrician with references.",
    status: "contratado",
    publisher: { id: "u22", name: "Fernando Torres", avatar: "🧑" },
    publisherVerified: true,
    applicationsCount: 5,
    createdAt: "2026-09-15T13:00:00Z",
  },
  {
    id: "t8",
    title: "Grocery and errands for an elderly neighbor",
    description:
      "I need someone trustworthy to bring groceries twice a week and run small errands for my grandmother. She lives in the same building as me, so it's a short trip. Cash on delivery.",
    category: "groceries",
    modality: "por_hora",
    amount: 35,
    units: 2,
    negotiable: true,
    includesTransport: true,
    includesMaterials: false,
    includesMeals: false,
    startDate: "2026-09-22",
    schedule: "10:00 AM – 12:00 PM",
    zone: "Zona 3",
    city: "Ciudad de Guatemala",
    peopleNeeded: 1,
    requirements: "Patient and reliable; references appreciated.",
    status: "contratado",
    publisher: { id: "u23", name: "Ana Martínez", avatar: "👩‍🦰" },
    publisherVerified: true,
    applicationsCount: 7,
    createdAt: "2026-09-14T08:45:00Z",
  },
  {
    id: "t9",
    title: "Deep cleaning after renovation",
    description:
      "Post-construction cleaning of a 2-bedroom apartment: paint spatters, dust, and debris on floors and windows. It took about 8 hours for one person.",
    category: "cleaning",
    modality: "por_proyecto",
    amount: 800,
    negotiable: false,
    includesTransport: false,
    includesMaterials: true,
    includesMeals: false,
    startDate: "2026-09-10",
    schedule: "8:00 AM – 4:00 PM",
    zone: "Zona 14",
    city: "Ciudad de Guatemala",
    peopleNeeded: 1,
    requirements: "Experience with post-construction cleaning.",
    status: "completado",
    publisher: { id: "u24", name: "Patricia Morales", avatar: "👩" },
    publisherVerified: true,
    applicationsCount: 4,
    createdAt: "2026-09-05T10:15:00Z",
  },
  {
    id: "t10",
    title: "Weekly garden care for one month",
    description:
      "Monthly plan: mow the lawn, prune, and water the plants weekly for four consecutive weeks. Payment each week or all at once, as you prefer.",
    category: "gardening",
    modality: "por_semana",
    amount: 350,
    units: 4,
    negotiable: true,
    includesTransport: false,
    includesMaterials: true,
    includesMeals: false,
    startDate: "2026-10-05",
    endDate: "2026-10-26",
    schedule: "9:00 AM – 12:00 PM",
    zone: "Zona 12",
    city: "Ciudad de Guatemala",
    peopleNeeded: 1,
    requirements: "Gardening experience.",
    status: "publicado",
    publisher: { id: "u25", name: "Sandra Paredes", avatar: "👩‍🔧" },
    publisherVerified: true,
    applicationsCount: 3,
    createdAt: "2026-09-21T07:00:00Z",
  },
];

export const mockApplications: JobApplication[] = [
  {
    id: "a1",
    jobId: "t1",
    name: "Diego Herrera",
    avatar: "🚚",
    presentation:
      "Hello, I've helped move two families this year and I have a lot of energy. I can come at 7am to help you pack before the truck arrives.",
    experience: "3 years helping with moves in Zona 10 and 15.",
    proposedPrice: 250,
    verified: true,
    createdAt: "2026-09-20T14:00:00Z",
  },
  {
    id: "a2",
    jobId: "t2",
    name: "María López",
    avatar: "🌿",
    presentation:
      "Hi, I garden on weekends. I have my own trimming tools if needed and I'm careful with plants.",
    experience: "2 years caring for family gardens.",
    verified: true,
    createdAt: "2026-09-20T16:10:00Z",
  },
  {
    id: "a3",
    jobId: "t5",
    name: "Carlos Vega",
    avatar: "📦",
    presentation:
      "I've worked in a distribution center before, so I'm used to shelving and orders. I'm available the whole week.",
    experience: "6 months in a warehouse in Zona 13.",
    verified: true,
    createdAt: "2026-09-18T12:00:00Z",
  },
  {
    id: "a4",
    jobId: "t5",
    name: "Marta Gómez",
    avatar: "👩",
    presentation:
      "I'm punctual and strong. I can start Monday if you confirm and I'm fine with the schedule.",
    verified: false,
    createdAt: "2026-09-18T17:30:00Z",
  },
];

export const mockReviews: Review[] = [
  {
    id: "r1",
    jobId: "t9",
    reviewerName: "Patricia Morales",
    reviewerAvatar: "👩",
    rating: 5,
    comment:
      "She arrived on time, worked the full 8 hours, and the apartment looked brand new. I'd hire her again without hesitation.",
    role: "employer",
    createdAt: "2026-09-12T09:00:00Z",
  },
  {
    id: "r2",
    jobId: "t9",
    reviewerName: "Lucía Pineda",
    reviewerAvatar: "🧑‍🎨",
    rating: 4,
    comment:
      "Great attention to detail, she also cleaned the window frames. Communication was smooth the whole way.",
    role: "employer",
    createdAt: "2026-09-11T18:20:00Z",
  },
  {
    id: "r3",
    jobId: "t7",
    reviewerName: "Fernando Torres",
    reviewerAvatar: "🧑",
    rating: 5,
    comment:
      "He diagnosed the problem and fixed the wiring in one afternoon. Fair price and very professional.",
    role: "employer",
    createdAt: "2026-09-23T09:30:00Z",
  },
];

export const mockWorkers: WorkerProfile[] = [
  {
    id: "w1",
    name: "Roberto Méndez",
    avatar: "🔧",
    title: "Home repairs & appliance technician",
    bio: "I repair washing machines, refrigerators and basic plumbing. I bring my own tools and I'm used to working in apartments across Zona 9, 10 and 14.",
    categories: ["repairs", "services"],
    modalities: ["por_proyecto", "por_hora"],
    rate: 400,
    rateModality: "por_proyecto",
    negotiable: true,
    zone: "Zona 10",
    city: "Ciudad de Guatemala",
    availability: "Mon–Sat, 8 AM – 6 PM",
    experience: "8 years as an appliance technician.",
    verified: true,
    rating: 4.8,
    completedJobs: 47,
    status: "disponible",
    createdAt: "2026-08-12T10:00:00Z",
  },
  {
    id: "w2",
    name: "María López",
    avatar: "🌿",
    title: "Gardening & lawn care",
    bio: "Lawn mowing, pruning, weeding and complete garden cleanup. I have professional tools and a rake for big yards.",
    categories: ["gardening"],
    modalities: ["por_hora", "por_semana"],
    rate: 40,
    rateModality: "por_hora",
    negotiable: false,
    zone: "Zona 15",
    city: "Ciudad de Guatemala",
    availability: "Weekends and two afternoons a week",
    experience: "3 years gardening for family homes and condos.",
    verified: true,
    rating: 4.9,
    completedJobs: 32,
    status: "disponible",
    createdAt: "2026-08-20T09:00:00Z",
  },
  {
    id: "w3",
    name: "Lucía Pineda",
    avatar: "🧹",
    title: "Professional house cleaning",
    bio: "Deep cleaning for homes and offices: bathrooms, kitchens, floors and windows. I bring my own cleaning supplies and masks.",
    categories: ["cleaning", "services"],
    modalities: ["por_dia", "recurrente"],
    rate: 250,
    rateModality: "por_dia",
    negotiable: true,
    zone: "Zona 3",
    city: "Ciudad de Guatemala",
    availability: "Any day, mornings preferred",
    experience: "5 years cleaning private homes.",
    verified: true,
    rating: 4.9,
    completedJobs: 68,
    status: "disponible",
    createdAt: "2026-07-02T14:30:00Z",
  },
  {
    id: "w4",
    name: "Diego Herrera",
    avatar: "🚚",
    title: "Movers helper & freight",
    bio: "Furniture moves, truck loading and unloading. I'm strong and careful with fragile items; I can bring a hand truck.",
    categories: ["moving", "transport"],
    modalities: ["por_hora", "por_dia"],
    rate: 30,
    rateModality: "por_hora",
    negotiable: true,
    zone: "Zona 8",
    city: "Ciudad de Guatemala",
    availability: "Weekends and evenings",
    experience: "4 years helping with removals.",
    verified: false,
    rating: 4.6,
    completedJobs: 21,
    status: "disponible",
    createdAt: "2026-09-01T08:00:00Z",
  },
  {
    id: "w5",
    name: "Manuel López",
    avatar: "⚡",
    title: "Electrician (licensed)",
    bio: "Electrical repairs, wiring replacements and safety checks. I work until the problem is solved and I always leave a written quote free.",
    categories: ["services", "repairs"],
    modalities: ["por_proyecto"],
    rate: 450,
    rateModality: "por_proyecto",
    negotiable: false,
    zone: "Zona 5",
    city: "Ciudad de Guatemala",
    availability: "Mon–Fri, 2 PM – 8 PM",
    experience: "12 years as a licensed electrician.",
    verified: true,
    rating: 4.7,
    completedJobs: 55,
    status: "disponible",
    createdAt: "2026-06-18T11:00:00Z",
  },
  {
    id: "w6",
    name: "Carlos Vega",
    avatar: "📦",
    title: "Warehouse & errands help",
    bio: "I organize shelves, prepare orders and run errands. Punctual, responsible and available for short-term weekly assignments.",
    categories: ["services", "groceries"],
    modalities: ["por_dia", "por_semana"],
    rate: 1200,
    rateModality: "por_semana",
    negotiable: true,
    zone: "Zona 13",
    city: "Ciudad de Guatemala",
    availability: "Full week, 9 AM – 5 PM",
    experience: "6 months in a distribution center.",
    verified: true,
    rating: 4.5,
    completedJobs: 12,
    status: "ocupado",
    createdAt: "2026-08-30T09:30:00Z",
  },
  {
    id: "w7",
    name: "Julia Ramírez",
    avatar: "🧑‍🍳",
    title: "Cooking & meal prep support",
    bio: "I cook traditional Guatemalan food and prepare weekly menus. I can shop for ingredients and cook at your home.",
    categories: ["groceries", "community"],
    modalities: ["por_hora", "recurrente"],
    rate: 60,
    rateModality: "por_hora",
    negotiable: true,
    zone: "Zona 4",
    city: "Ciudad de Guatemala",
    availability: "Mon–Sat mornings",
    experience: "10 years cooking for families.",
    verified: true,
    rating: 4.8,
    completedJobs: 40,
    status: "disponible",
    createdAt: "2026-07-25T16:00:00Z",
  },
  {
    id: "w8",
    name: "Pedro Juárez",
    avatar: "🔨",
    title: "Carpenter (doors, frames, furniture)",
    bio: "Custom furniture, door and frame repairs, shelving and small woodworking. I can work on site with my own tools.",
    categories: ["carpentry"],
    modalities: ["por_proyecto"],
    rate: 350,
    rateModality: "por_proyecto",
    negotiable: true,
    zone: "Zona 1",
    city: "Ciudad de Guatemala",
    availability: "Mon–Sat, 8 AM – 5 PM",
    experience: "9 years as a carpenter.",
    verified: false,
    rating: 4.4,
    completedJobs: 26,
    status: "disponible",
    createdAt: "2026-08-05T13:00:00Z",
  },
  {
    id: "w9",
    name: "Sara Cordón",
    avatar: "🐕",
    title: "Pet sitter & dog walker",
    bio: "Walks, feeding and care for dogs and cats while you're away. I send daily photos and I'm very patient with shy pets.",
    categories: ["pets"],
    modalities: ["por_hora", "por_dia"],
    rate: 25,
    rateModality: "por_hora",
    negotiable: false,
    zone: "Zona 9",
    city: "Ciudad de Guatemala",
    availability: "Every day, flexible",
    experience: "3 years caring for pets.",
    verified: true,
    rating: 5.0,
    completedJobs: 18,
    status: "disponible",
    createdAt: "2026-08-15T10:00:00Z",
  },
  {
    id: "w10",
    name: "Óscar Tzún",
    avatar: "🛠️",
    title: "Construction & masonry helper",
    bio: "Helper for small constructions, tiling, painting and general repairs. I adapt quickly and follow instructions well.",
    categories: ["services", "repairs", "carpentry"],
    modalities: ["por_dia", "por_semana"],
    rate: 200,
    rateModality: "por_dia",
    negotiable: true,
    zone: "Zona 6",
    city: "Ciudad de Guatemala",
    availability: "Mon–Sat, 7 AM – 5 PM",
    experience: "5 years in construction crews.",
    verified: true,
    rating: 4.7,
    completedJobs: 33,
    status: "disponible",
    createdAt: "2026-09-05T09:00:00Z",
  },
];

export const mockWorkerReviews: WorkerReview[] = [
  {
    id: "wr1",
    workerId: "w1",
    reviewerName: "María García",
    reviewerAvatar: "👩",
    rating: 5,
    comment:
      "He fixed my washing machine the same afternoon. Clear price before starting, no surprises.",
    createdAt: "2026-09-10T10:00:00Z",
  },
  {
    id: "wr2",
    workerId: "w1",
    reviewerName: "Carlos López",
    reviewerAvatar: "👨",
    rating: 4,
    comment: "Punctual and professional. Recommended for appliance repairs.",
    createdAt: "2026-08-28T15:00:00Z",
  },
  {
    id: "wr3",
    workerId: "w2",
    reviewerName: "Carmen Ruiz",
    reviewerAvatar: "👩‍🦱",
    rating: 5,
    comment:
      "The garden looks incredible. She even trimmed edges that others ignored.",
    createdAt: "2026-09-15T09:00:00Z",
  },
  {
    id: "wr4",
    workerId: "w3",
    reviewerName: "Patricia Morales",
    reviewerAvatar: "👩",
    rating: 5,
    comment:
      "Deep cleaning was spotless and she brought everything. I book her every two weeks now.",
    createdAt: "2026-09-08T14:00:00Z",
  },
  {
    id: "wr5",
    workerId: "w9",
    reviewerName: "Ana Martínez",
    reviewerAvatar: "👩‍🦰",
    rating: 5,
    comment: "My dog loves her. Daily photos and zero stress while I traveled.",
    createdAt: "2026-09-02T11:00:00Z",
  },
];
